### ISSUE TITLE
I want to implement an Emacs Port

### ISSUE THREAD

**Issue by ema2159** [sailorhg/fairyfloss#33]
Hi Amy, I want to port your theme to Emacs, the thing is, where can I find an ordered showcase of the color palette? For example, check Solarized's web page: https://ethanschoonover.com/solarized/

**Comment by gempesaw** [comment]
there are some related issues! https://github.com/sailorhg/fairyfloss/pull/3 https://github.com/sailorhg/fairyfloss/pull/28

**Comment by ema2159** [comment]
@gempesaw I've checked those out, the thing is, an "official" pallette like in other themes would be really useful with information like what color should be used for variables, functions, background etc

**Comment by ema2159** [comment]
Done, it's been added to: https://github.com/hlissner/emacs-doom-themes
