### ISSUE TITLE
Share Custom Font?

### ISSUE THREAD

**Issue by cttnguyen** [sailorhg/fairyfloss#35]
Hi, 
I'm an R user and was hoping to use this theme in RStudio. I've got it mostly working, but I'd like to install a custom font to get the cursive letters. Right now, I've got all the colors and italics working from fairyfloss. Do you mind sharing what font you used? I don't think I was able to find it in the repo, but I know that could just be my own user error. 
Thanks!

**Comment by ChrisW-B** [comment]
@cttnguyen I think the font is operator mono! You'd have to buy a license for that one, but JetBrains mono is a good free replacement if you want slightly less cursive but still kind of cursive italics https://www.jetbrains.com/lp/mono/

**Comment by cttnguyen** [comment]
Thanks!
