### ISSUE TITLE
Xcode Support?

### ISSUE THREAD

**Issue by ashfurrow** [sailorhg/fairyfloss#8]
Hi there! I'm a big fan of this colour scheme! I've recreated it in Xcode, since I do most of my work there. It's a bit crude since Xcode colour themes don't allow the level of customization that Atom and Sublime do. Here's what it looks like:

<img width="1548" alt="screen shot 2016-05-15 at 5 28 36 pm" src="https://cloud.githubusercontent.com/assets/498212/15276890/9db3f44a-1ac2-11e6-9608-de79505c55ce.png">

(I've put a copy of it in a [gist](https://gist.github.com/ashfurrow/0eabfb70d7114d98a74213f829c78218).)

I'd love any feedback you have on it, and with your blessing, I'd like to publish it to [Alcatraz](https://github.com/alcatraz/Alcatraz), the community-organized plugin manager for Xcode. I'm happy to host the file or to send a PR to add it here. Thanks again!

**Comment by sailorhg** [comment]
@ashfurrow i'm glad you like it & thanks for re-creating it in xcode! if you make a PR to host it here, i'll approve it!
